apiVersion: v1
kind: Service
metadata:
  name: {{ include "status-page.fullname" . }}
  labels:
    {{- include "status-page.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "status-page.selectorLabels" . | nindent 4 }}
